### ISSUE TITLE
`importPaths` not working as expected

### ISSUE THREAD

**Issue by lucoel** [figma/code-connect#10]
First, congrats on the launch! 🎉 Super excited to see where Dev Mode is going. Of course I couldn't stop myself from playing around yesterday during the announcement and in general it was super easy to set up. 

But I got stuck while trying to update the `importPaths` for our component package. After copying the [configuration example](https://github.com/figma/code-connect/blob/main/react/README.md#configuration) from the React documentation I noticed that some keys seem to miss quotes. My setup now looks like this:

### `figma.config.json`
```json
{
  "codeConnect": {
    "include": [
      "packages/xyz/src/components/**"
    ],
    "exclude": [],
    "react": {
      "importPaths": {
        "./*": "@org/xyz"
      }
    }
  }
}
```

### `Button.figma.tsx`
```tsx
import figma from '@figma/code-connect'
import { Button } from './Button' 
```

Uploading to Figma immediately worked, but no matter what I specify at `importPaths`, I get nothing but `import { Button } from "./Button` in Dev Mode.

It could definitely be me, I would be thankful for a hint in the right direction!

**Comment by lucoel** [comment]
Thanks to both of you, @plotka @karlpetersson! The suggestion worked straight away, looking forward to the next release(s).

**Comment by ptomas-figma** [comment]
@lucoel we just release 0.1.1 with the fix for the issue as Karl mentioned above. Please let us know and things are working now.
