### ISSUE TITLE
Running "npx figma connect" results in the error "Failed to fetch components from Figma (ERR_BAD_REQUEST): 400 undefined" 

### ISSUE THREAD

**Issue by ktamken** [figma/code-connect#102]
Hello.

I am trying to connect to Figma components using Code Connect.
After running the "npx figma connect" command and specifying the access token and working directory,
I specify the URL of the Figma component, but the connection fails with the error message "Failed to fetch components from Figma (ERR_BAD_REQUEST): 400 undefined".

I tried to display debug logs with the "--verbose" option, but it seems that no debug logs were output.

My environment is as follows, please tell me the cause of the error and how to deal with it.

Environment:
OS: Windows 10 22H2
npm: 10.8.2
node_module:
    @figma/code-connect@1.0.2
    react-dom@18.3.1
    react-router-dom@6.25.0
    react@18.3.1

Network: Company network with proxy

**Comment by ktamken** [comment]
Hello.

I'm adding some information to this issue.

Based on the error message, I checked the method defined in the link code:
https://github.com/figma/code-connect/blob/main/cli/src/connect/wizard/run_wizard.ts#L52

My understanding is that it extracts the "FileKey" from the URL, creates a REST API endpoint, and executes the API (GET /code_connect/<FileKey>/cli_data).
I created and executed a code that runs the REST API independently in the same configuration and network environment as described in the issue.
I expected it to end with "ERR_BAD_REQUEST" as in the previous issue, but it ended normally.

Is there any difference between using the code_connect module and executing the REST API directly?

Also, is the following README content relevant?
https://github.com/figma/code-connect/blob/main/README.md#common-issues

**Comment by rrabherufigma** [comment]
Hi @ktamken. To help us investigate further, could you please submit a support request on [Figma support](https://help.figma.com/hc/en-us/requests/new) and provide the filekey.

**Comment by ktamken** [comment]
Hello.

@rrabherufigma 
Thank you for your reply.
This issue could be due to my network environment, so I will check it on my end. 
If I still need to contact you, I will submit a support request to Figma support.

I will close this issue for now.

**Comment by cth18012017** [comment]
Hello, I have the same problem "Figma (ERR_BAD_REQUEST): 400 undefined".
@ktamken what was the solution for you? What do you config in your "network environment"?

**Comment by markalanevans** [comment]
I was hoping you did.
