### ISSUE TITLE
Storybook integration prerequisites are unclear

### ISSUE THREAD

**Issue by bitfella** [figma/code-connect#107]
Hi,
I've successfully managed to make Figma Code Connect work on a React project via dedicated *.figma.tsx file, but for some reason I can't make it work with the Storybook integration.

I am using:
- Mac OS Sonoma 14.5
- `react`: 16.13.1
- `storybook`: 7.6.19
- `@figma/code-connect` 1.0.3
- `@storybook/addon-designs` 8.0.3

This is my `figma.config.json` placed in the root of the project:
```
{
  "codeConnect": {
    "parser": "react",
    "include": ["packages/dls/components/**"]
  }
}
```
This is the component:
```
import React from 'react'
import PropTypes from 'prop-types'

import { StyledLink, StyledDivider } from './Breadcrumb.styled'

/**
 * A component that displays a breadcrumb.
 *
 * @param {object} props - a props object
 * @param {boolean} props.hasDivider - whether the divider should appear or not
 * @param {string} props.divider - the divider
 * @param {string} props.text - the text
 * @returns {React.Element} Breadcrumb element
 */
const Breadcrumb = ({ hasDivider = true, divider = '/', text }) => {
  return (
    <StyledLink>
      {text} {hasDivider && <StyledDivider>{divider}</StyledDivider>}
    </StyledLink>
  )
}

Breadcrumb.propTypes = {
  hasDivider: PropTypes.bool,
  divider: PropTypes.string,
  text: PropTypes.string
}

export default Breadcrumb

```
and this is the Storybook file:
```
import React from 'react'
import figma from '@figma/code-connect'

import Breadcrumb from './Breadcrumb'

export const Primary = () => {
  return <Breadcrumb hasDivider divider='/' text='Breadcrumb' />
}

export default {
  component: Breadcrumb,
  title: 'Atoms/Breadcrumb',
  parameters: {
    design: {
      type: 'figma',
      url: 'https://www.figma.com/design/[...]&m=dev',
      examples: [Primary],
      props: {
        hasDivider: figma.boolean('divider?'),
        divider: figma.enum('divider', {
          '/': '/',
          '>': '>'
        }),
        text: figma.string('text'),
        state: figma.enum('state', {
          enabled: 'enabled',
          hover: 'hover'
        })
      }
    },
    argTypes: {
      hasDivider: { control: 'boolean' },
      text: { control: 'string' },
      divider: {
        control: {
          type: 'select',
          options: ['/', '>']
        }
      }
    },
    args: {
      hasDivider: true,
      text: 'Breadcrumb',
      divider: '/'
    }
  }
}
```
now when I launch the following command on the terminal from the root of the project:
```
npx figma connect publish --token FIGMA_ACCESS_TOKEN --verbose
```
what I get back is the following message:
```
Config file found, parsing /Users/m/Projects/codeconnect using specified include globs
Story files found:

No Code Connect files found in /Users/m/Projects/codeconnect - Make sure you have configured `include` and `exclude` in your figma.config.json file correctly, or that you are running in a directory that contains Code Connect files.
```
For some reason, it seems like the aforementioned Storybook file can't be recognised as a Figma Code Connect file while the other suggested approach (creating a dedicated Figma Code Connect typescript file in the component folder) works smoothly and the components gets successfully connected with its Figma counterpart.

Now my question is: in [this documentation page](https://github.com/figma/code-connect/blob/main/cli/README.md#integrating-with-storybook) an "Existing Storybook Integration" is mentioned; what is unclear to me is whether all the steps listed in [this page](https://help.figma.com/hc/en-us/articles/360045003494-Storybook-and-Figma) must be completed to make sure Storybook files can be recognised as Figma Code Connect files, such as Storybook project published on Chromatic, being listed as a collaborator in Chromatic, and so on.

Thanks

**Comment by bitfella** [comment]
Hello @dentrado, thanks for quickly getting back at me. It's exactly as you said indeed, the problem was the file extension. This codebase I'm spiking on is entirely in JS and so the Storybook files are, and from the documentation I didn't understand that the Storybook files had to be strictly TS, while I understood that the Figma file had to be. That's why the Figma file was working and the Storybook file not! Thanks, made my day! 😊

**Comment by uiyuvi** [comment]
@dentrado , I see you mentioned *stories.tsx is only supported, 
 is it possible  make code connect to work with *.stories.js or *.stories.jsx
