### ISSUE TITLE
The package name is off in Package.swift, should be repo name = code-connect

### ISSUE THREAD

**Issue by doozMen** [figma/code-connect#109]
https://github.com/figma/code-connect/blob/444f438600b08f4dce46655ed1a76ac0c508c7fb/Package.swift#L8

The name her should be `code-connect` as that is the package name.

Including the dependency in a target is difficult otherwise as the Package name `Figma` does not work

**Comment by jyyang0** [comment]
Hi @doozMen, thanks for your interest in code connect -- I can see that including the dependency in a target is a bit confusing, but here if you use the repo name I believe SPM will resolve it correctly. So you could add the dependency like
 
```swift
.target(
    name: "MyLibrary",
    dependencies: [
        .product(name: "Figma", package: "code-connect")
    ]
),
```
or 
```swift
.target(
    name: "MyLibrary",
    dependencies: [
        "Figma"
    ]
),
```

**Comment by doozMen** [comment]
Yes it does. It used to have a name property when you add the dependency. I was pointing out that the name should be the package name that can include multiple products like the Figma library now is one. So changing the name on your end in the Package.swift should have no impact. Just ease my, and maybe others uneasy fuzzy feeling when having to use a different name then the package.swift states. That's for your quick reply

**Comment by doozMen** [comment]
So closing the issue is not really what I was expecting sorry. As it is an issue, maybe a weird things SPM but the package name should be the repo name. More debate here https://forums.swift.org/t/what-exactly-is-the-real-name-of-this-package/64868
