### ISSUE TITLE
Support using a Figma prop without documenting it.

### ISSUE THREAD

**Issue by fraincs** [figma/code-connect#112]
I have some instances where my components have implicit props. Take this React component: 

```
<Link variant="primary" size="sm">My Text</Link>
```

Currently in Figma the Link component has a Label prop, although my component will take anything between my component tag and render it.

I would like the possibility to hide the label prop showing in dev mode as it's not a valid prop.

<img width="311" alt="image" src="https://github.com/user-attachments/assets/60061df3-3850-4436-8ead-8a5d9fed5e86">

**Comment by rrabherufigma** [comment]
Hi @fraincs , are you seeking to hide the label prop on specific variants?

**Comment by fraincs** [comment]
> Hi @fraincs , are you seeking to hide the label prop on specific variants?

I was trying to avoid having to display the Label prop as we don't use it, but I found a way.

**Comment by rrabherufigma** [comment]
Ok 👍 . I will close this issue
