### ISSUE TITLE
Streamline Figma file URL for use in Figma connect

### ISSUE THREAD

**Issue by zcoffin86** [figma/code-connect#113]
`figma connect` CLI should be able to figure out the file URL, or the Web App or Desktop App should make it easier to get a properly formatted URL. I just went through the process and every URL I could find to copy+paste from either of those sources was _not_ of the right format. I resulted in talking with ChatGPT to figure out how to manually create a valid link based on all the invalid links I was seeing.  If it must be manually created, at least update the readme to that effect.

I was at the point where the CLI is asking me `What is the URL of the Figma file containing your design system library?`. I didn't know how to get this URL. All the URLs I had entered were apparently invalid, prompting the message `Please enter a valid Figma file URL`.

- Code Connect CLI version [use `npx figma -V` if using React, or `figma -V` otherwise, to get the version of your CLI]
  - 1.0.3
- Operating system
  - Windows 11

**Comment by rrabherufigma** [comment]
Hi @zcoffin86 , this should be the url in the address bar e.g. https://www.figma.com/design/abc

**Comment by zcoffin86** [comment]
ok well it's working now, but i don't think I've done anything differently. Previously when I pasted in links of that format I got that error message. Strange.

**Comment by mrlubos** [comment]
@rrabherufigma where do you see the URL if you're using the Figma app?

**Comment by ptomas-figma** [comment]
@mrlubos in the Figma desktop app you can right click on the file tab and select `Copy Link` from the menu.

**Comment by mrlubos** [comment]
@ptomas-figma I see, thanks! Honestly it would be more discoverable in the regular File dropdown, I didn't even think to right-click tabs
<img width="384" alt="Screenshot 2024-08-13 at 9 53 19 AM" src="https://github.com/user-attachments/assets/0adcc8b4-ac02-417c-817a-924a70f3d05a">
