### ISSUE TITLE
error occurred by using "figma.boolean" w/"figma.textContent"

### ISSUE THREAD

**Issue by jongjunpark** [figma/code-connect#117]
my component's `Text` property is boolean. If true, a text component named _Text_ exists, and if false, that text component disappears. I set "undefined" when `Text` property is false, but it causes an error.
I think code connect validates the true case even when it's false.
How to fix it?

- code
```javascript
figma.connect(
  Heading,
  "https://www.figma.com/...",
  {
    props: {
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
        Xlarge: "xLarge",
      }),
      text: figma.textContent("Title"),
      description: figma.boolean("Text", {
        false: undefined,
        true: figma.textContent("Text"),
      }),
      align: figma.enum("Align", {
        Default: "default",
        Center: "center",
      }),
    },
    example: (props) => <Heading {...props} />,
  },
);
```

- `description: figma.boolean("Text")`
    - true : using `figma.textContent`
    - false: `undefined` **(error occurred)**

- figma
    - `Text` propery: true
![image](https://github.com/user-attachments/assets/c2d61ad8-2bc9-4f87-b76a-8e26d9fd7f3b)

    - `Text` property: false
![image](https://github.com/user-attachments/assets/55d7f71e-a7eb-4d6f-bece-134e9b64056b)

**Comment by lauthieb** [comment]
+1 !

**Comment by karlpetersson** [comment]
This should be fixed in later versions of CC, but feel free to ping here again if you continue to see this issue
