### ISSUE TITLE
The custom `links` array is not showing up in Figma

### ISSUE THREAD

**Issue by andreiduca** [figma/code-connect#12]
While not currently documented, the source code shows support for a `links` property which is supposed to show up in Figma (but it currently does not):

```ts
  /**
   * A list of links that will display in Figma along with the examples
   */
  links?: FigmaConnectLink[]
```

**Comment by tomduncalf-figma** [comment]
Hey @andreiduca, yeah this one is not currently implemented in Figma itself. For now, you can add dev resources links instead. We are hoping to add support for rendering these soon!

**Comment by cscheffauer** [comment]
@tomduncalf-figma is there an ETA on when this is available in Figma itself? would be great to have this enabled.
