### ISSUE TITLE
figma.enum cannot map to decimal numbers

### ISSUE THREAD

**Issue by stacysun-cb** [figma/code-connect#121]
Hello! I have an issue with the `figma.enum` when passing decimal numbers in the value. All the decimal numbers below will show `0` in Figma design. Is there any workarounds?

```
figma.connect(
  Component,
  'https://...',
  {
    props: {
      value: figma.enum('value', {
        '100%': 1,
        '75%': 0.75,
        '50%': 0.5,
        '25%': 0.25,
        '0%': 0,
      }),
    },
    example: (props) => <Component {...props} />,
  },
);
```

- Code Connect CLI version: 1.0.4
- Operating system: macos

**Comment by ptomas-figma** [comment]
Hi @stacysun-cb! Thanks for the message. We'll be adding support for this in an upcoming version.

**Comment by ptomas-figma** [comment]
This is now supported as part of the 1.0.6 release.
