### ISSUE TITLE
Info about figma.tsx template function

### ISSUE THREAD

**Issue by kmartinezmedia** [figma/code-connect#133]
- Code Connect CLI version: 1.0.5
- Operating system: macOS Sonoma  14.6.1

👋  I was having a look at source code and was interested in understanding more about what the `figma.tsx` template function does. There is a brief mention in parser_template_helpers.ts:

> We recursively call `figma.tsx` on the value as it itself is an array of
> CODE/INSTANCE sections, so we need to run it through the template string
> function otherwise this would just output `[object Object]` for the value.
> The template string handler function handles flattening nested arrays.

Is this all this template function is responsible for or does it do some other magic under the hood? I understand this is an internal type of thing, but would be really helpful to better understand what that is responsible for - even a comment in parser_template_helpers.ts which showed a simple input > output example would be really helpful.

**Comment by jyyang0** [comment]
Hi @kmartinezmedia ! Thanks for bringing this to our attention. The documentation about our intermediary template format is something we're looking to improve in the near future.

For this bit specifically, as you've identified the template function essentially just builds up the code connect string and handles flattening nested arrays. There is a bit of extra logic that handles things like adding braces `{}` around arrays of child code connect files (for example, when using a `figma.children` helper), but the underlying use of this is just that it converts the intermediary template format into the code that should be rendered on Figma.
