### ISSUE TITLE
Ability to mark *.figma.tsx files as private

### ISSUE THREAD

**Issue by siddharthkul** [figma/code-connect#137]
👋 Hi team,

I've been using the Figma CLI script to auto-generate Figma files for Code Connect, which has been very helpful for integrating our design system with our development workflow.

However, I've encountered an issue where generating and uploading a large number of files risks getting throttled by Figma servers due to the volume of uploads. To manage this, it would be great to have a way to mark specific files as private during the generation process, either via a CLI flag or some configuration option. This would allow me to control which files are public and reduce the risk of hitting upload limits.

Is this something that could be added in a future update? It would significantly help in managing larger projects and avoiding server-side throttling.

Thanks!
Sid

**Comment by ptomas-figma** [comment]
Hi Sid, thanks for reaching out. To clarify, you're getting the issue when running the `figma connect` CLI? Could you share a screenshot of what you see on the terminal?

**Comment by siddharthkul** [comment]
Hey @ptomas-figma, my initial thoughts were if there was a property in *.figma.tsx to mark it as private - allowing us to control which files are public and reduce the risk of hitting upload limits.

However we ended up using the include/exclude properties in the figma.config.json to get around this.
