### ISSUE TITLE
Publish Specific Folder in Figma Code Connect

### ISSUE THREAD

**Issue by siddharthkul** [figma/code-connect#138]
- Code Connect CLI version: 1.0.5
- Operating system: MacOS

Hey team, I've been using the publish command in Figma Code Connect to push my Figma files to our design system. However, I've encountered a challenge while developing individual components.

Currently, when I run the publish command, it appears to publish all Figma files from the root folder. While this is useful in some cases, it can be problematic when I'm only working on a single component within a specific folder.

The documentation mentions that the publish command should read from the current folder, but this doesn’t seem to be working as expected. Despite being in a specific folder, it still publishes all files from the root directory.

Would it be possible to add or fix this functionality so that developers can target a specific folder or set of files? 

Thanks!
Sid

**Comment by jyyang0** [comment]
Hey @siddharthkul, one thing you can try is do either use the `--dir` argument to specify a specific folder, or use a `config.json` file that has an `include` path in it which will allow you to specify a list of glob paths to narrow down the specific folders you want to work in (or exclude). This can be passed into the CLI using the --config argument. An example of this would be :

```json
{
  "codeConnect": {
    "parser": "react",
    "include": ["path/to/components/**"],
    "exclude": ["test/**", "docs/**", "build/**"],
  }
}
```
