### ISSUE TITLE
Map multiple nested Figma properties to one prop 

### ISSUE THREAD

**Issue by alisonjoseph** [figma/code-connect#141]
In Figma we have two toggles on our tab items, one for Dismissible and another for Dismissible + Icon. These both map to the same React property. I've solved it temporarily by this `dismissable={tab.dismissable} dismissable={tab.dismissableWithIcon}`.

Ideally I'd like to be able to do something like
`dismissable: figma.boolean('Dismissible') || figma.boolean('Dismissible + Icon'),` and just have the one prop `dismissable={tab.dismissable}`

*Simplified code snippet of our Tabs component. 
```jsx
figma.connect(
  Tabs,
  'https://www.figma.com.....',
  {
    props: {
      children: figma.children(['_Horizontal tabs items']),
      tab: figma.nestedProps('_Horizontal tabs items', {
        dismissable: figma.boolean('Dismissible'),
        dismissableWithIcon: figma.boolean('Dismissible + Icon'),
      }),
    },
    example: ({ children, tab }) => (
      <Tabs dismissable={tab.dismissable} dismissable={tab.dismissableWithIcon}>
        <TabList>
          {children}
        </TabList>
      </Tabs>
    ),
  }
);
```
![Screenshot 2024-08-23 at 8 54 58 AM](https://github.com/user-attachments/assets/88feb3c9-7d35-4bee-92d8-545923999c59)

**Comment by karlpetersson** [comment]
Hey @alisonjoseph, thanks for the feedback! You should be able to nest `figma.boolean` to achieve this behaviour, like so
```
dismissable: figma.boolean("Dismissible", {
  true: true,
  false: figma.boolean("Dismissible + Icon")
}),
```

Let me know if this works for you.

**Comment by alisonjoseph** [comment]
Thanks @karlpetersson, that worked perfectly.
