### ISSUE TITLE
can I scaffold React state from children?

### ISSUE THREAD

**Issue by ericandrewscott** [figma/code-connect#151]
For some of our more complex components, is there a way we can cobble together React state from children? For example, we have a Tabs component...

1. There is a parent Tabs component.
2. There is a child Tab component.

I can get the child Tab components to render with the appropriate state, which could be `Selected`, `Unselected` or `Disabled`, but I want to help our engineers to render some state inside the Figma , something like:
```
figma.connect(
  Tabs,
  "https://www.figma.com/design/<OBFUSCATED>",
  {
    props: {
      ...sharedTabsProps,
      tabs: figma.children(["⚙️ Equal width tab"]),
    },
    example: ({ backgroundColor, withBorder, tabs }) => {
      const [activeTab, setActiveTab] = React.useState(<CHILD_WITH_SELECTED_STATE>);

      return (
        <Tabs backgroundColor={backgroundColor} withBorder={withBorder}>
            {tabs}
        </Tabs>
      );
    },
  },
);
```

How would I do something like that?

- Code Connect CLI version: 1.0.6
- Operating system: OSX

**Comment by slees-figma** [comment]
Hey @ericandrewscott! Thanks for the question. If I'm understanding correctly, would `CHILD_WITH_SELECTED_STATE` be an identifier for whichever tab has e.g. state: "Selected"? And a followup question, would that identifier be the tab layer name, or a property?

Right now I don't think we have a way to dynamically select a value from a list like that, so maybe an alternative could be leaving instruction in a comment, e.g.:
```typescript
const [activeTab, setActiveTab] = React.useState(/* Tab ID goes here */);
```

**Comment by ericandrewscott** [comment]
Yeah, that will work as a stop gap.
