### ISSUE TITLE
imports property not working in figma connect file

### ISSUE THREAD

**Issue by siddharthkul** [figma/code-connect#159]
👋 Hi team, I just installed the latest code-connect version and noticed all our imports erroring as shown in attached image.

We were previously on 1.0.6 and it worked.

Thanks! --sid

<img width="1075" alt="Screenshot 2024-09-10 at 8 57 58 PM" src="https://github.com/user-attachments/assets/c449d108-35d8-40ce-8a28-53acb328d7ff">

Please provide:
- Code Connect CLI version: 1.1.12
- Operating system: MacOS
- Code Connect file, Figma design and/or relevant code snippet that could help us get more context
  - If you prefer not to share those publicly please reach out via the [Figma support](https://help.figma.com/hc/en-us/requests/new?ticket_form_id=360001744374)

**Comment by tomduncalf-figma** [comment]
Hey @siddharthkul, apologies for the issue here. 

Our latest update had a bug in the Typescript typings. We've released v1.1.3 to fix this, and also put tests in place to hopefully prevent it happening again. 

Please let us know if you continue to experience any issues!
