### ISSUE TITLE
Dyamic props based on booleans

### ISSUE THREAD

**Issue by sekeidesign** [figma/code-connect#17]
I'm not sure how this would work, but it would be great to be able to dynamically remove props from the examples based on other boolean values.

In this example, when `description?` is `false`, the Figma Props UI is smart enough to hide the `description` prop entirely, even though that prop still has a value. However, I'm not able to hide this prop in code, so the component snippet is wrong and will add text to the component that shouldn't be there at all.

![CleanShot 2024-04-17 at 18 49 03@2x](https://github.com/figma/code-connect/assets/59372630/d6d154f5-bed4-49c1-9ff3-3838805b8609)
![CleanShot 2024-04-17 at 18 48 33@2x](https://github.com/figma/code-connect/assets/59372630/50c5e4ca-0fcc-4b89-94c9-5823ce79550c)

**Comment by tomduncalf-figma** [comment]
Thanks @mryechkin, this is correct! If you have issues with this @sekeidesign, please let us know.

We are going to look at adding some more documentation on common patterns like this, as it's not necessarily obvious.
