### ISSUE TITLE
How to switch between different component based on the different value of same figma variable

### ISSUE THREAD

**Issue by anuradha9712** [figma/code-connect#170]
In figma I have variable "Type" which has 2 possible values: Image & Text

**Type: Text**
<img width="572" alt="image" src="https://github.com/user-attachments/assets/7d997306-2b61-4160-a57d-723c95c73f70">

**Type: Image:**
<img width="1082" alt="image" src="https://github.com/user-attachments/assets/a3f2c637-ce6d-4435-a8b9-78dbf723ba2f">

& in my codebase I have map it to 2 different components: `<PlaceholderImage />` & `<PlaceholderParagraph />`

How to correctly map it in figma connect?

I have tried the following approach:
```
props: {
      round: figma.enum('Shape', {
              Round: true,
              Square: false,
            }),
      component: figma.enum('Type', {
              Image: <PlaceholderImage />,
              Text: <PlaceholderParagraph />,
            }),
},
example: ({component}) => <>{component}</>
```

this works fine but how to pass rest of the props (`round` in this case) to the rendered component?

Or if there is any better approach to achieve the same?

**Comment by anuradha9712** [comment]
@ericandrewscott Any help would be appreciated.

**Comment by ericandrewscott** [comment]
@anuradha9712 Sorry, I do not work for Figma.

**Comment by rkieru** [comment]
I would think the easiest approach for your use case would be to leverage Code Connects Variant feature.

```
variant: { Type: 'Image' },
props: {
      round: figma.enum('Shape', {
              Round: true,
              Square: false,
            }),
      component: figma.enum('Type', {
              Image: <PlaceholderImage />,
              Text: <PlaceholderParagraph />,
            }),
},
example: ({ round }) => <PlaceholderImage round={ round } />
```

And then repeat this for `<PlaceholderParagraph />`

Here is the relevant React documentation https://github.com/figma/code-connect/blob/main/docs/react.md#variant-restrictions

**Comment by anuradha9712** [comment]
Thanks @rkieru this approach works perfectly fine!! 🎉
