### ISSUE TITLE
[Angular] [HTML] Keep exact formatting of Inputs instead of forcing lower case

### ISSUE THREAD

**Issue by massi08** [figma/code-connect#172]
We are using code-connect with angular. We use the html parser for that but some of our inputs are converted to lowercase.
We would like to keep the exact formatting instead.

for e.g: 
```
 example: (props) => html`
      <component [a11YAriaLabel]="${props.ariaLabel}">
      </component>
    `,
```
In this case `[a11YAriaLabel]="${props.ariaLabel}"` is converted to `[a11yarialabel]="label"` on the code preview in figma.

**Comment by massi08** [comment]
Maybe a solution is to provide a new config option to keep the exact formatting of props when needed. It would be nice to have at the root config level and at the "story" level as well.
This is a big issue for us at the moment since code connect produces non working code in some scenarios.

**Comment by massi08** [comment]
@tomduncalf-figma any news on this?

**Comment by slees-figma** [comment]
Hey @massi08, sorry for the slow response to this one! We're looking into this at the moment and should have a fix soon.

**Comment by miguel-ama** [comment]
Cool. We were having this same issue. Thanks for the fix.
