### ISSUE TITLE
Nesting figma.nestedProps

### ISSUE THREAD

**Issue by takanopontaro** [figma/code-connect#178]
Hi Figma team,

I got the following error message when I nested figma.nestedProps.

`nestedProps can not be nested inside another nestedProps call, instead, pass the deeply nested layer name at the top level`

I am not sure about `the deeply nested layer name`. May I ask about it?

----

@figma/code-connect: 1.1.4
macOS Sonoma 14.4.1

**Comment by takanopontaro** [comment]
Oh, I understand. It means I can directly specify the name of the child layer.
I was able to connect.

**Comment by slees-figma** [comment]
Thanks @takanopontaro, let us know if you experience further issues
