### ISSUE TITLE
[SwiftUI] Generate code can't compile because of Issues with @FigmaEnum and @FigmaInstance

### ISSUE THREAD

**Issue by mackoj** [figma/code-connect#186]
After running the figma connect create command, the generated loader.figma.swift file includes a few @FigmaEnum and @FigmaInstance property wrappers. However, these are not compiling as expected.

The generated code looks like this:

```swift
  @FigmaEnum(
    "Size",
    mapping: [
      "Extra Large": extraLarge,
      "Small": small,
      "Medium": medium,
      "Large": large
    ]
  )
  var size: Any
```

To resolve the compilation issue, I manually modified the code to map these values to our custom types:

```swift
  @FigmaEnum(
    "Size",
    mapping: [
      "Extra Large": LoaderTheme.Size.extraLarge,
      "Small": LoaderTheme.Size.small,
      "Medium": LoaderTheme.Size.medium,
      "Large": LoaderTheme.Size.large
    ]
  )
  var size: LoaderTheme.Size
```

However, this introduced a new error, as shown in the screenshot below:

![Capture d’écran 2024-10-16 à 11 21 54](https://github.com/user-attachments/assets/3fb988bd-dd15-4343-8314-3fab66936330)

I fixed this issue by adjusting the implementation as follows:

```swift
  @FigmaEnum(
    wrappedValue: LoaderTheme.Size.extraLarge,
    "Size",
    mapping: [
      "Extra Large": LoaderTheme.Size.extraLarge,
      "Small": LoaderTheme.Size.small,
      "Medium": LoaderTheme.Size.medium,
      "Large": LoaderTheme.Size.large
    ]
  )
  var size: LoaderTheme.Size
```

This resolved the compilation issue. However, when I attempt to publish, I encounter the following error:

`Couldn't parse connected component Loader_doc with error: The variable size is missing the Figma component property name.`

To resolve this, I reverted back to the original form:
```swift
  @FigmaEnum(
    "Size",
    mapping: [
      "Extra Large": LoaderTheme.Size.extraLarge,
      "Small": LoaderTheme.Size.small,
      "Medium": LoaderTheme.Size.medium,
      "Large": LoaderTheme.Size.large
    ]
  )
  var size: LoaderTheme.Size
```

Now, while it no longer compiles, it does allow me to successfully publish.

Environement:
- Code Connect CLI version: 1.1.4
- Operating system: macOS Sonoma 14.7
- Code Connect file

Can you help resolve this issue? Thanks in advance for your assistance!

**Comment by tomduncalf-figma** [comment]
Hey @mackoj, thanks for reporting this. We're looking into it and will get back to you ASAP!

**Comment by tomduncalf-figma** [comment]
Hey @mackoj, you need to specify an initial value for your variable. Something like:

```
  @FigmaEnum(
    "Size",
    mapping: [
      "Extra Large": LoaderTheme.Size.extraLarge,
      "Small": LoaderTheme.Size.small,
      "Medium": LoaderTheme.Size.medium,
      "Large": LoaderTheme.Size.large
    ]
  )
  var size: LoaderTheme.Size = LoaderTheme.Size.medium
```

The error Xcode gives isn't very helpful but in my testing, this was the cause of it. Can you let us know if this helps?
