### ISSUE TITLE
[SwiftUI] Feature Request: Support for @FigmaImage in Component Generation

### ISSUE THREAD

**Issue by mackoj** [figma/code-connect#187]
When generating components, Figma currently supports `@FigmaString`, `@FigmaBoolean` and `@FigmaInstance` property wrappers. However, there is no equivalent for handling images. It would be useful to have a `@FigmaImage` property wrapper to support components that require image assets.

This feature would enable us to show how to properly integrate and manage images through our API when working with Figma-generated components.

Environement:
- Code Connect CLI version: 1.1.4
- Operating system: macOS Sonoma 14.7
- Code Connect file

Thanks in advance for considering this request!

**Comment by tomduncalf-figma** [comment]
Hey @mackoj, I'm not sure how this would work as your images will be hosted on your own servers rather than on Figma's, and there's no way to specify an external image URL in Figma. Or did you have something else in mind?

**Comment by mackoj** [comment]
> there's no way to specify an external image URL in Figma
