### ISSUE TITLE
why "Failed to fetch components from Figma: unable to get local issuer certificate" occur??

### ISSUE THREAD

**Issue by siosio34** [figma/code-connect#189]
Please provide:

- Code Connect CLI version 1.2.0
- Operating system Mac OS, React

An error message similar to the title occurs, but I am curious about when this error message occurs.

**Comment by siosio34** [comment]
I followed the code and it seems that the issue occurs below. Is the SSL certificate of the figma API server incorrect? Or is this issue only happening to me?

<img width="578" alt="image" src="https://github.com/user-attachments/assets/51aa2b77-64e8-4b3d-bf8d-1a248bb54bf0">

**Comment by tomduncalf-figma** [comment]
Hi @siosio34, I suspect you are behind a proxy/firewall which modifies HTTPS certificates, so the certificate chain cannot be validated. 

You could try setting the environment variable `NODE_TLS_REJECT_UNAUTHORIZED` to `0`, e.g. by running `figma` like `NODE_TLS_REJECT_UNAUTHORIZED=0 npx figma connect...`. This does mean that your connection to Figma will be potentially insecure, so please ensure this is expected and that you're OK with this.

**Comment by siosio34** [comment]
Thank you for your reply. The issue has been resolved. Thank you for making a great product.
@tomduncalf-figma
