### ISSUE TITLE
How to use `figma.string` within React code

### ISSUE THREAD

**Issue by origami-z** [figma/code-connect#200]
- Code Connect CLI version - 1.2.1
- Operating system MacOS

In Figma, we have a boolean and text prop controlling a text layer. In code, we would need to render additional code around the text. e.g.

When boolean is off, we want the React code to be

```
<Banner>
    <Text>{body}</Text>
</Banner>
```

When boolean is on, we want the React code to be

```
<Banner>
    <Text><strong>{title here}</strong></Text>
    <Text>{body}</Text>
</Banner>
```
I know I can't run logic within code connect, so I attempted below

```
figma.connect(
....
     title: figma.boolean("👁️ Title", {
        true: (
          <Text><strong>{figma.string("✏️ Title")}</strong></Text>
        ),
        false: undefined,
      }),
...
// example
  <Banner>
    {props.title}
    {props.body}
  </Banner>
```

In Figma UI Dev mode, the `figma.string("✏️ Title")}` bits is rendered literally, instead reading the actual code from text layer.

Am I using the API by mistake? Or is this feature possible?

**Comment by rrabherufigma** [comment]
Hi @origami-z . The best way to solve this right now is to use a [variant restriction ](https://github.com/figma/code-connect/blob/main/docs/react.md#variant-restrictions) on figma.boolean("👁️ Title") . However it is on our roadmap to support scenarios such as this one.

**Comment by origami-z** [comment]
> Hi @origami-z . The best way to solve this right now is to use a [variant restriction ](https://github.com/figma/code-connect/blob/main/docs/react.md#variant-restrictions) on figma.boolean("👁️ Title") . However it is on our roadmap to support scenarios such as this one.

@rrabherufigma thanks for coming back. I'm not sure how to achieve this using variant restriction. Is it meant to have 2 connection like below?

```
figma.connect(Banner, 'https://...', {
  variant: { "👁️ Title": true },
  props: { 
     // ... other props
  },
  example : // ...
})
figma.connect(Banner, 'https://...', {
  variant: { "👁️ Title": false },
  props: { 
     // ... other props
  },
  example : // ...
})
```

**Comment by ptomas-figma** [comment]
That's right. Each connection will only be rendered for the specific variant indicated:

```
figma.connect(Banner, 'https://...', {
  variant: { "👁️ Title": true },
  props: { 
     title: figma.string("✏️ Title"),
     // ... other props including body
  },
  example : (props) =>   <Banner>
    <Text><strong>{props.title}</string></Text>
    {props.body}
  </Banner>
})
figma.connect(Banner, 'https://...', {
  variant: { "👁️ Title": false },
  props: { 
     // ... props including body
  },
  example : <Banner>
    {props.body}
  </Banner>
})
```

**Comment by origami-z** [comment]
Thank you. I will try this very soon.
