### ISSUE TITLE
[React] Using figma variables in functions

### ISSUE THREAD

**Issue by Sh031224** [figma/code-connect#202]
I want to use a figma variable in a function.
So, I wrote the code as follows, and the results came out as intended.

```tsx
figma.connect(Slider, '<FIGMA_SLIDER>', {
  props: {
    firstLabel: figma.string('┗ First'),
    lastLabel: figma.string('┗ Last'),
  },
  example: ({ firstLabel, lastLabel }) => (
    <Slider
      label={({ index }) =>
        index === 0 ? <>{firstLabel}</> : <>{lastLabel}</>
      }
    />
  ),
});
```

![image](https://github.com/user-attachments/assets/980a4353-2439-4e0a-a711-1edb7b758970)

However, I wanted to exclude the react fragment, and when I removed the part that was wrapped by the react fragment, the variable names were exposed, leading to unintended behavior.

```tsx
figma.connect(Slider, '<FIGMA_SLIDER>', {
  props: {
    firstLabel: figma.string('┗ First'),
    lastLabel: figma.string('┗ Last'),
  },
  example: ({ firstLabel, lastLabel }) => (
    <Slider
      label={({ index }) =>
        index === 0 ? firstLabel : lastLabel
      }
    />
  ),
});
```

![image](https://github.com/user-attachments/assets/07501965-cb9a-4d0f-a0bc-31f9e1ab05b2)

Is there a way to resolve this issue?
Meaningless react fragments are making me suffer.

- Code Connect CLI version [1.2.2]
- Operating system [Mac OS 14.5]

**Comment by ptomas-figma** [comment]
Hi @Sh031224 

Could you try this as the example 

```typescript
example: (props) => (
    <Slider
    label={({ index }) =>
      index === 0 ? props.firstLabel : props.lastLabel
    }
  />
)
```

**Comment by Sh031224** [comment]
@ptomas-figma 

I applied your example and it works fine.
Is the reason it behaves differently because of how code connect parses it?
