### ISSUE TITLE
While publishing getting -> Failed to upload to Figma (500): 500 Internal server error

### ISSUE THREAD

**Issue by abhishek-jha-lab49** [figma/code-connect#210]
Please provide:

- Code Connect CLI version - **1.2.2**
- Operating system - **Windows**
- Code Connect file - https://www.figma.com/design/k84gM2BFqWwXMYOEojWjB2/Figma-Code-Connect?node-id=8-5&t=YjLLmxpBNR028G7E-1

I was able to connect and create a figma file for my code in react but while publishing the same back to code connect I am getting "**Failed to upload to Figma (500): 500 Internal server error**"

Logs
No config file found in C:\Workspace\React\figma-code-connect, proceeding with default options
Using "react" parser as package.json containing a "react" dependency was found in C:\Workspace\React\figma-code-connect. If this is incorrect, please check you are running Code Connect from your project root, or add a `parser` key to your config file. See https://github.com/figma/code-connect for more information.
(node:2932) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Workspace\React\figma-code-connect\src\components\button\Button.figma.tsx
Validating Code Connect files...
All Code Connect files are valid (2020ms)
Uploading to Figma...
Failed to upload to Figma (500): 500 Internal server error
Please raise any bugs or feedback at https://github.com/figma/code-connect/issues.

[Button.figma.tsx.txt](https://github.com/user-attachments/files/17771329/Button.figma.tsx.txt)
[Button.tsx.txt](https://github.com/user-attachments/files/17771330/Button.tsx.txt)

**Comment by tomduncalf-figma** [comment]
Hey @abhishek-jha-lab49, sorry for the inconvenience here, we had a bug on the Code Connect server-side. A fix has been deployed, could you check if this is resolved for you now please? If you're still having issues, please reopen the issue.
