### ISSUE TITLE
Support for Jetpack Compose

### ISSUE THREAD

**Issue by dd-bmunge** [figma/code-connect#22]
Thanks team for providing this capability. We're really excited about starting to integrate this for our React Web and iOS SwiftUI component implementation. This is more a question of when we could expect the same support for Jetpack Compose to begin exposing the same capability for our Android implementation. 🚀

**Comment by ptomas-figma** [comment]
Hey, thanks for your interest in Code Connect!

We’re planning to add support for more frameworks in the near future. We can’t say yet exactly which frameworks or when, but it’s helpful for us to hear from the community to help us decide where to focus, so please feel free to add a 👍 to this issue if you are also interested in support for Jetpack Compose. I will leave this issue open to track interest.

Code Connect is also designed to be extensible, and the community will be able to create their own plugins to support frameworks and languages which we don’t natively support. More details about how to build these plugins will be coming soon!

**Comment by ptomas-figma** [comment]
Jetpack Compose is now part of the Code Connect supported languages: https://github.com/figma/code-connect/tree/main/compose
