### ISSUE TITLE
Render Icons as React Components When Used in Another Component

### ISSUE THREAD

**Issue by SatyamBansal** [figma/code-connect#221]
In our setup, we use a `IconWrapper` component to render our icons, and the icons themselves are defined as React components in the codebase. For example, if I want to render an `ExampleIcon`, we use the following code:  

```jsx
<IconWrapper source={ExampleIcon} />
```

This works perfectly with Code Connect. However, the issue arises when I want to use these icons as props in another component.  

For instance, our `Button` component accepts a `leftIcon` prop like this:  

```jsx
<Button 
  leftIcon={ExampleIcon} 
  {...props} 
/>
```  

Internally, the `Button` component uses `IconWrapper` and applies additional props, so we do **not** pass `IconWrapper` directly to the `leftIcon` prop.  

### Problem with Code Connect  

When using Code Connect, it generates the following output:  

```jsx
<Button 
  leftIcon={<IconWrapper source={ExampleIcon} />} 
  {...props} 
/>
```  

This is incorrect for our use case. How can I configure Code Connect to properly handle this scenario?  

### Environment Details  

- **Code Connect CLI version**: 1.2.0  
- **Operating system**: macOS  

---  

This version is cleaner, has a proper structure, and emphasizes the key details.

**Comment by karlpetersson** [comment]
Hey @SatyamBansal, we recently introduced `getProps` ([docs](https://www.figma.com/code-connect-docs/react/#accessing-icon-props-in-parent-component)) that allows you to access props in nested components for this purpose. For example, you can expose a `source` prop like so:

```
figma.connect(
  "<icon url>",
  {
    props: {
      source: ExampleIcon,
    },
    example: () => <IconWrapper source={ExampleIcon}  />,
  }
);
```

And then in your parent Button component:
```
    props: {
      iconProps: figma.instance("Icon").getProps(),
    },
    example: ({ iconProps }) => <Button 
      leftIcon={iconProps.source} 
    />
```

Let me know if this helps.

**Comment by SatyamBansal** [comment]
@karlpetersson i have tried this approach, the issue is in generated code, `leftIcon` is being passed  string prop rather than a react component whereas while defining `source` in Icon code connect file it was a React component.

Here is the complete snippet generated by code connect after following said approach. 

```
import { AnkButton } from "ankanUI/index"
import { AUIIcon } from "ankanUI/index"
import ArrowRight from "assets/vectors/ankanUI/ArrowRight"
import Plus from "assets/vectors/ankanUI/Plus"

<AnkButton
    size="large"
    variant="primary"
    type="positive"
    leftIcon="Plus"
    rightIcon="ArrowRight"
    onPress={() => {}}
>
    Label
</AnkButton>
``` 

Expectation: 
```
leftIcon={Plus}
 rightIcon={ArrowRight}
```

**Comment by karlpetersson** [comment]
@SatyamBansal we very recently released a new version of the CLI that should fix this issue - did you recently update? If not please try updating the CLI and hopefully that solves the issue. If not let me know and we'll look into it

**Comment by SatyamBansal** [comment]
Hi, it works fine with the latest CLI update. Thank you for getting back to me so quickly, closing this..
