### ISSUE TITLE
Support for HTML

### ISSUE THREAD

**Issue by andershagbard** [figma/code-connect#27]

**Comment by karlpetersson** [comment]
HTML is now supported, but please feel free to create new issues if there are things we've missed, or more features needed to fully support your use case.

---

You can provide a code connect example without passing the first React component parameter:
```
figma.connect("<url>", {
  props: { /* ... */ },
  example: () => (<button></button>)
})
```

Additionally we've added the [`className` helper](https://github.com/figma/code-connect/blob/main/cli/README.md#classname) to allow you to map figma props to a className string.
