### ISSUE TITLE
Can you target "Text" layers as "children"?

### ISSUE THREAD

**Issue by l-campbell** [figma/code-connect#30]
## Question

I have a Figma component that uses a "Text" layer instead of a property. With code connect, is there a way to target this layer to map to a coded component prop? In my scenario, I'm trying to map this to the `label` prop in the coded component. I've tried using `figma. children()` with the name of the layer with no success, I know this isn't the intended here.

### Layers

All the nested layers in this tree are either row or column layouts.

<img width="320" alt="Screenshot 2024-04-23 at 04 31 19" src="https://github.com/figma/code-connect/assets/4479852/45e1e946-0d4f-4b61-8690-0c96fc414161">

### Render

<img width="150" alt="Screenshot 2024-04-23 at 04 32 11" src="https://github.com/figma/code-connect/assets/4479852/04734d35-1058-4249-8b3a-912678a7df63">

### Info
<img width="220" alt="Screenshot 2024-04-23 at 04 32 21" src="https://github.com/figma/code-connect/assets/4479852/a016b4dc-53c5-46fb-a605-4caed704fd17">

### Code connect
<img width="297" alt="Screenshot 2024-04-23 at 04 38 05" src="https://github.com/figma/code-connect/assets/4479852/57723af3-db4f-4325-912b-493bd65a1a8d">

**Comment by tomduncalf-figma** [comment]
Hi @l-campbell, right now we don't support this I'm afraid, but it's on our roadmap as we know some design system do use overrides like this instead of props. I'll keep this issue open so we can update you on progress.

**Comment by mryechkin** [comment]
Just chiming in here to say that our design team also uses a similar approach in some components, so it's great to hear it will be supported 🎉

**Comment by alisonjoseph** [comment]
+1 for wanting this

**Comment by alisonjoseph** [comment]
Confirmed this works for my above example with Tabs. 🙌

However I'm struggling to get the value for an example that has the text layer nested more deeply. Any solution for this without updating the actual Figma component itself?
<img width="341" alt="Screenshot 2024-06-18 at 1 36 22 PM" src="https://github.com/figma/code-connect/assets/2753488/482a6005-37aa-475a-b858-9b2833d5ac34">

**Comment by tomduncalf-figma** [comment]
Hey @alisonjoseph, happy to hear it's working for you. You should be able to reference this nested layer using `figma.nestedProps`, something like:

```
nested: figma.nestedProps("_Number input base", {
  text: figma.textContent("Text")
})
```

which would then be available as `props.nested.text`

**Comment by alisonjoseph** [comment]
@tomduncalf-figma Nested property support is 🔥 worked perfectly, thanks!
