### ISSUE TITLE
Documentation CLI `--verbose` arg not supported

### ISSUE THREAD

**Issue by ktabors** [figma/code-connect#37]
In the [publishing](https://emojipedia.org/winking-face) section of the ./react/README.md, `--verbose` is listed as an option. This doesn't work. When I checked the [code](https://github.com/figma/code-connect/blob/main/react/src/commands/connect.ts#L22-L33) for the args I couldn't find `--verbose`. I did find `-d --debug` which does work. [Link to debug arg.](https://github.com/figma/code-connect/blob/main/react/src/commands/connect.ts#L29)
The ./react/README.md needs to be updated.

**Comment by karlpetersson** [comment]
Thanks for flagging this!

**Comment by tomduncalf-figma** [comment]
This will be fixed in the next release
