### ISSUE TITLE
Is `text` in the "Dynamic code snippets" documentation a typo or a feature?

### ISSUE THREAD

**Issue by wosephjeber** [figma/code-connect#42]
First off, my team is super excited about this tool! From our experimentation so far it's looking really promising as a way to help bridge the gap between designers and engineers.

I'm confused by the `text` prop in the ["Dynamic code snippets" documentation](https://github.com/figma/code-connect/blob/e58ebc1be158e2b91e3f75e7b4afab28c3f046d7/react/README.md#dynamic-code-snippets), though:

```jsx
import figma from '@figma/code-connect'

figma.connect(Button, 'https://...', {
  props: {
    label: figma.string('Text Content'),
    disabled: figma.boolean('Disabled'),
    type: figma.enum('Type', {
      Primary: 'primary',
      Secondary: 'secondary',
    }),
  },
  example: ({ disabled, text, type }) => {
    return (
      <Button disabled={disabled} type={type}>
        {text}
      </Button>
    )
  },
})
```

That code snippet also [shows up in the blog post](https://www.figma.com/blog/introducing-code-connect/#meeting-developers-where-they-are).

Is this a typo, and the `text` prop in the `example` should really be `label` from the props mapping? Or is there a special `text` prop that gets passed to the `example` for all components?

**Comment by ptomas-figma** [comment]
That is, indeed, a typo! Either the `label` prop should be `text` or the `text` argument should be `label`. We'll fix in the next release. Thanks!
