### ISSUE TITLE
Difference between Code Connect and Code Snippet Editor plugin

### ISSUE THREAD

**Issue by AniketBhadane** [figma/code-connect#47]
With both Code Connect and Code Snippet Editor, we can see the corresponding code for the components. So what makes Code Connect different than Code Snippet Editor?

**Comment by tomduncalf-figma** [comment]
Hey @AniketBhadane

Code Connect and plugins like Code Snippet Editor are both tools to customize the code output in Dev Mode. But they’re slightly different, and one might be better for your use case than the other.

With Code Connect, code snippets reside within your own codebase, ensuring their accuracy by utilizing real components. This setup facilitates easy collaboration and ensures that code snippets remain up-to-date as your codebase evolves, as any team member can update the associated documents and see connected code snippets in Dev Mode. Code Connect might be right for you if you’re willing to invest a little more for easier onboarding and adoption overall.

Code Snippet Editor (and other similar codegen plugins) generate component code, but don't actually connect to your codebase. Plugins do not require any setup and are really easy to use as an individual designer or developer. It’s a great option if you want to try out the usefulness of more customized code or are maybe working with a framework not currently supported by Code Connect.

Let us know if you need more information!
