### ISSUE TITLE
Support for React Native

### ISSUE THREAD

**Issue by DIntriglia** [figma/code-connect#5]
Excited to put forward my recommendation for React Native support.

**Comment by tomduncalf-figma** [comment]
Hey @DIntriglia, you should already be able to use React Native code with Code Connect – it uses the same syntax as regular React, so I don't think you should have any issues. I'll make sure we test this and add it to the documentation to avoid confusion in future, so thanks for calling this out. 

If you do have any problems, please feel free to either reopen this issue or create a new one and we'll be happy to help.
