### ISSUE TITLE
Nested component variant restriction bug

### ISSUE THREAD

**Issue by alisonjoseph** [figma/code-connect#54]
I'm seeing a bug with nested components connected with variant restrictions.

When I view the Code Connect code from the parent component the child component code ignores the variant restrictions  and just renders the first code connect code sample. However if I view each nested component individually the correct code appears. 

### Breadcrumb (parent)
<img width="1331" alt="Screenshot 2024-05-16 at 1 02 31 PM" src="https://github.com/figma/code-connect/assets/2753488/4fb496bc-a7cd-4927-ae10-981a04fc05f6">

### vs. Breadcrumb item (child)
<img width="1328" alt="Screenshot 2024-05-16 at 1 03 07 PM" src="https://github.com/figma/code-connect/assets/2753488/9e68986b-03a9-45b0-9603-8feb40dfa2f0">

<img width="1333" alt="Screenshot 2024-05-16 at 1 03 32 PM" src="https://github.com/figma/code-connect/assets/2753488/93145ca9-aff0-41e6-b40b-a8b2de730fde">

My figma.tsx file is here https://github.com/carbon-design-system/carbon/pull/16348/files#diff-38ea233b4b838e2f4e41e8bbd621f7524ce7496d17ef86aa3826b33f7157f9b3R16

**Comment by ptomas-figma** [comment]
Hi Alison, thanks for the report! The team is aware of this issue and we'll be hopefully solving it soon. Will keep you posted in this thread when the fix gets released.

**Comment by alisonjoseph** [comment]
Confirmed this is fixed, thanks ya'll! 🥳
