### ISSUE TITLE
Adding props which the Figma component does not contain throws an error

### ISSUE THREAD

**Issue by konki-vienna** [figma/code-connect#65]
Documentation says, that I can e.g. add custom properties such as [classNames](https://github.com/figma/code-connect/blob/main/cli/README.md#classname) or [textContent](https://github.com/figma/code-connect/blob/main/cli/README.md#text-content) to the code-connect-file (Button.figma.tsx).

However, when I do that, it throws an error:
Adding `label: figma.textContent('Label'),` into the props section and trying to publish it, throws the error
'Validation failed for Button (https://www.figma.com/design/…/G-Web?node-id=319-4760): The property "undefined" does not exist on the Figma component'

**Comment by ptomas-figma** [comment]
Hi @konki-vienna, thanks for reporting. Could you double check if you're using the latest release of Code Connect with `figma -V` ?

**Comment by konki-vienna** [comment]
I am using 0.2.1 - which is the latest version afaik.
However, this is another weird thing, because although I am using 0.2.1 code connect keeps complaining that I am running 0.2.0 - see screenshot attached.
<img width="990" alt="Bildschirmfoto 2024-06-19 um 20 18 19" src="https://github.com/figma/code-connect/assets/5039952/98cfd427-94e5-4b72-b663-c847b9cd2484">

**Comment by konki-vienna** [comment]
We can close this issue - I reverted everything, started from scratch managed to update to v.1.0.0 and the other issues are gone as well. :)

**Comment by tomduncalf-figma** [comment]
Hey @konki-vienna, actually this confusion was on us, apologies! The update command we showed was for _globally_ updating the package, but if you are in a React project, you probably have it _locally_ installed (in `package.json`).

The confusion here is that `npx figma` will run the local version from your `node_modules`, whereas `figma` will run the global version.

We just released v1.0.1 which updates the messaging on updates to be correct. 

If you're only working with React, we recommend you just locally install Code Connect in your project, so you can `npm uninstall -g @figma/code-connect` and just use the version in your `package.json`, running it with `npx figma`.

Apologies again for the confusion here and thank you for bringing this to our attention!

**Comment by konki-vienna** [comment]
Thanks for your reply.
I learned the hard way to not install @figma/code-connect globally because I could not commit any of our code to our repository anymore. 😅
Even when I checked out a totally different branch. 😬
I don't remember the entire error message, but it was something like "URL.parseSomething".

Luckily I managed to uninstall everything and set it up (just locally) from scratch.
