### ISSUE TITLE
"Booleans" which are actually Variants in Figma seem to cause an issue with code connect if they are not "true/false" but "yes/no"

### ISSUE THREAD

**Issue by konki-vienna** [figma/code-connect#66]
We have a Button component in Figma with two different sizes: default and small.
As this affects the height of the Button component it cannot be a Boolean prop, but has to be a Variant prop (with just two values).
In the Figma properties panel, there is a Switch "Small" which can be toggled off (for default) or on (for small).
The values of a Variant prop in Figma (used as a boolean) can be either "yes"/"no" or "true"/"false".

Our Button component used "yes"/no"", which is fine for the Figma component. However, the boolean in code-connect always returned "false".

By changing the prop's values in Figma to "True"/"False", I managed to get the code-connect property to work:

`small: figma.boolean('Small', {`
`     true: Button.SIZE.SMALL,`
`           false: undefined,`
`.    }),`

So, it seems to me whilst Figma is not having any issues with Variant props named "Yes"/"No" (instead of "True"/"False"), code connect expects "True"/"False".

**Comment by karlpetersson** [comment]
Hi @konki-vienna, thanks for reporting this! We're aiming to have this fixed in the next release.
