### ISSUE TITLE
How to not output 'className=""'?

### ISSUE THREAD

**Issue by konki-vienna** [figma/code-connect#67]
We have a Button component that behaves differently on different backgrounds.
With the Figma prop Background = "On Product" a className "g-inverted" needs to be added to the React code.
With the Figma prop "Background = "On Neutral" no className is needed.

The code-connect code
className: figma.className([
     figma.enum('Background', { 'On Product': 'g-inverted' }),
     figma.enum('Background', { 'On Neutral': undefined }),
]),
adds the "g-inverted" className property correctly, if Background="On Product", however if Background ="On Neutral", the property 'className=""' gets added to the code snippet.

Have I misconfigured something or can't this be achieved?

**Comment by konki-vienna** [comment]
![Bildschirmfoto 2024-06-20 um 16 18 16](https://github.com/figma/code-connect/assets/5039952/a7d147c0-5afa-4bba-894b-28a9dbc688e3)
![Bildschirmfoto 2024-06-20 um 16 18 27](https://github.com/figma/code-connect/assets/5039952/9e3e9fc9-5737-433b-9706-d794ae32504c)

**Comment by karlpetersson** [comment]
Hey @konki-vienna! Yeah this is a bug, unfortunately `undefined` values resolve to empty strings. However you might be able to get around this if it's just a single string like in your example, by using only `enum`:
```
className: figma.enum('Background', {
    'On Product': 'g-inverted'
})
```

We'll look into fixing this though!
