### ISSUE TITLE
Should figma.instance, figma.children and figma.nestedProps wait for the layer to also become undefined instead of breaking?

### ISSUE THREAD

**Issue by nrenard** [figma/code-connect#71]
I'm trying to create some docs using figma code connect and some components have a component inside when a variant it's true and when it's false the component disappears and the code connect breaks...

Example:

We have this default variants:
<img width="286" alt="Screenshot 2024-06-24 at 8 27 24 PM" src="https://github.com/figma/code-connect/assets/22799737/bb07b340-ba92-4e5a-8308-96775a3d0270">

And the layer tree looks like this:
<img width="496" alt="Screenshot 2024-06-24 at 8 28 21 PM" src="https://github.com/figma/code-connect/assets/22799737/d8484ba8-2c6d-441b-bd40-dc5f06297c62">

And when we turn Leading variant into false the layer tree looks like this:
<img width="494" alt="Screenshot 2024-06-24 at 8 29 11 PM" src="https://github.com/figma/code-connect/assets/22799737/0a358fd9-f75a-4a91-a9eb-1313a01de402">

---

I'm trying to get the icon inside these ". Item / Leading Node" using a figma.instance because Icon it's also a "variant"... When i see a component with the Leading=true it work pretty well but when i see a component with Leading=false it break all the code connect of that component...

Here is the code example:
```tsx
import React from "react"
import figma from "@figma/code-connect"

import { Component } from "@components"

figma.connect(
  Component,
  "...",
  {
    props: {
      leadingIcon: figma.nestedProps('. Item / Leading Node', {
        icon: figma.instance('Icon')
      })
    },
    example: (props) => <Component {...props} leadingIcon={props?.leadingIcon.icon} />,
  },
)
```

**Comment by karlpetersson** [comment]
Hey! This should be working after a recent change, if you wrap the `nestedProps` call in a boolean:
```
props: {
  leadingIcon: figma.boolean("Leading", {
     true: figma.nestedProps('. Item / Leading Node', { icon: ... })
     false: { icon: undefined }
    })
}
```

Not that you'll want to provide a fallback object in the `false` case

**Comment by tomduncalf-figma** [comment]
I am going to close this issue but please let us know if you continue to see this issue
