### ISSUE TITLE
Error: Failed to upload to Figma

### ISSUE THREAD

**Issue by og2t** [figma/code-connect#9]
Hi,

Great stuff!

I am trying this but I got:

`Failed to upload to Figma (ERR_BAD_REQUEST): 403 Invalid scope(s): files:read. This endpoint requires the file_code_connect:write scope`

Is this the account/permissions issue or something else?
Thanks!

<img width="964" alt="Screenshot 2024-04-17 at 14 58 52" src="https://github.com/figma/code-connect/assets/28712/b0eb42b7-f191-4fee-9373-21fff2247ee9">

**Comment by og2t** [comment]
That was it thanks @lucoel. Would be good to update the docs with that screenshot in the token section 😊

**Comment by FEliuyg** [comment]
@lucoel why i did not see code connect in personal access token?how can i do to see this?

**Comment by FEliuyg** [comment]
sorry, my account is not Organization account!
